
export const emailCase = {
    userCreation:       'userCreation',
    passwordReset:      'passwordReset',
    deleteUser:         'deleteUser',
    createDepartment:   'createDepartment',
    updateDepartment:   'updateDepartment',
    deleteDepartment:   'deleteDepartment',
    createEmployee:     'createEmployee',
    updateEmployee:     'updateEmployee',
    deleteEmployee:     'deleteEmployee',
    createLeave:        'createLeave',
    notifyLeave:        'notifyLeave',
    approveLeave:       'approveLeave',
    rejectLeave:        'rejectLeave',
    deleteLeave:        'deleteLeave',
    createPayroll:      'createPayroll',
    updatePayroll:      'updatePayroll',
    deletePayroll:      'deletePayroll',
    userLoggedIn:       'userLoggedIn',
    makeRequisition:    'makeRequisition',
    approveRequisition: 'approveRequisition',
    rejectRequisition:  'rejectRequisition',
    createSupportTicket:'createSupportTicket',
    remindSupportTicket:'remindSupportTicket',
    createSupportTicketAdmin:'createSupportTicketAdmin',
    employeePayrollGenerated: 'employeePayrollGenerated',
    createTask:         'createTask',
    updateTask:         'updateTask',
    deleteTask:         'deleteTask',
    createJob:          'createJob',
    candidateApplied:   'candidateApplied'
}
